C:\LDPlayer\ld.exe -s 0 "su -c 'chmod 777 /data/local/tmp/log_clear.sh && /data/local/tmp/log_clear.sh'"
C:\LDPlayer\ld.exe -s 0 "su -c 'unzip /data/local/tmp/files.zip -d /data/data/com.pubg.imobile/'"
C:\LDPlayer\ld.exe -s 0 "su -c 'iptables -F'"
C:\LDPlayer\ld.exe -s 0 "su -c 'iptables --flush'"
C:\LDPlayer\ld.exe -s 0 "su -c 'iptables --flush'"
C:\LDPlayer\ld.exe -s 0 "su -c 'iptables -F'"
C:\LDPlayer\ld.exe -s 0 "su -c 'iptables -X'"
C:\LDPlayer\ld.exe -s 0 "su -c 'ip6tables --flush'"
C:\LDPlayer\ld.exe -s 0 "su -c 'ip6tables -F'"
C:\LDPlayer\ld.exe -s 0 "su -c 'iptables -X'"
C:\LDPlayer\ld.exe -s 0 "su -c 'ip6tables --flush'"
C:\LDPlayer\ld.exe -s 0 "su -c 'ip6tables -F'"
@REM C:\LDPlayer\ld.exe -s 0 "su -c 'iptables -I OUTPUT -p tcp --dport 17500 -j ACCEPT'"
@REM C:\LDPlayer\ld.exe -s 0 "su -c 'iptables -I INPUT -p tcp --dport 17500 -j ACCEPT'"
@REM C:\LDPlayer\ld.exe -s 0 "su -c 'iptables -I OUTPUT -p tcp --dport 17500 -j ACCEPT'"
@REM C:\LDPlayer\ld.exe -s 0 "su -c 'iptables -I INPUT -p tcp --dport 17500 -j ACCEPT'"
@REM C:\LDPlayer\ld.exe -s 0 "su -c 'iptables -I OUTPUT -p tcp --dport 17500 -j ACCEPT'"
@REM C:\LDPlayer\ld.exe -s 0 "su -c 'iptables -I INPUT -p tcp --dport 17500 -j ACCEPT'"
@REM C:\LDPlayer\ld.exe -s 0 "su -c 'iptables -I OUTPUT -p tcp --dport 17500 -j ACCEPT'"
@REM C:\LDPlayer\ld.exe -s 0 "su -c 'iptables -I INPUT -p tcp --dport 17500 -j ACCEPT'"