C:\LDPlayer\ld.exe -s 0 "su -c 'killall -q com.pubg.imobile'"
C:\LDPlayer\ld.exe -s 0 "su -c 'am force-stop com.pubg.imobile'"
C:\LDPlayer\ld.exe -s 0 "su -c 'chmod 777 /data/local/tmp/log_clear.sh && /data/local/tmp/log_clear.sh'"
taskkill /IM "dnplayer.exe" /F
taskkill /IM "BGMI Louncher.exe" /F
@REM C:\LDPlayer\ld.exe -s 0 "su -c 'rm -rf /sdcard/MT2'"
@REM C:\LDPlayer\ld.exe -s 0 "su -c 'rm -rf /sdcard/MIUI'"
@REM C:\LDPlayer\ld.exe -s 0 "su -c 'rm -rf /sdcard/tencent'"
@REM C:\LDPlayer\ld.exe -s 0 "su -c 'touch /sdcard/tencent'"
@REM C:\LDPlayer\ld.exe -s 0 "su -c 'rm -rf /sdcard/MidasOversea'"
@REM C:\LDPlayer\ld.exe -s 0 "su -c 'touch /sdcard/MidasOversea'"
@REM C:\LDPlayer\ld.exe -s 0 "su -c 'touch /sdcard/.backups'"
@REM C:\LDPlayer\ld.exe -s 0 "su -c 'rm -rf /sdcard/QTAudioEngine'"
@REM C:\LDPlayer\ld.exe -s 0 "su -c 'rm -rf /sdcard/Android/data/com.pubg.imobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/SaveGames/*.json'"
@REM C:\LDPlayer\ld.exe -s 0 "su -c 'rm -rf /sdcard/Android/data/com.pubg.imobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/UpdateInfo/*'"
@REM C:\LDPlayer\ld.exe -s 0 "su -c 'rm -rf /sdcard/Android/data/com.pubg.imobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Logs'"
@REM C:\LDPlayer\ld.exe -s 0 "su -c 'rm -rf /sdcard/Android/data/com.pubg.imobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Pandora'"
@REM C:\LDPlayer\ld.exe -s 0 "su -c 'touch /sdcard/Android/data/com.pubg.imobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Logs'"
@REM C:\LDPlayer\ld.exe -s 0 "su -c 'touch /sdcard/Android/data/com.pubg.imobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Pandora'"
@REM C:\LDPlayer\ld.exe -s 0 "su -c 'rm -rf /sdcard/Android/data/com.pubg.imobile/cache'"
@REM C:\LDPlayer\ld.exe -s 0 "su -c 'rm -rf /sdcard/Android/data/com.pubg.imobile/files/tbslog'"
@REM C:\LDPlayer\ld.exe -s 0 "su -c 'rm -rf /sdcard/Android/data/com.pubg.imobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Logs'"
@REM C:\LDPlayer\ld.exe -s 0 "su -c 'rm -rf /sdcard/Android/data/com.pubg.imobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Pandora'"
@REM C:\LDPlayer\ld.exe -s 0 "su -c 'rm -rf /sdcard/Android/data/com.pubg.imobile/files/cacheFile.txt'"
@REM C:\LDPlayer\ld.exe -s 0 "su -c 'rm -rf /data/data/com.pubg.imobile/*cache*'"
@REM C:\LDPlayer\ld.exe -s 0 "su -c 'rm -rf /data/data/com.pubg.imobile/app*'"
@REM C:\LDPlayer\ld.exe -s 0 "su -c 'rm -rf /data/data/com.pubg.imobile/databases'"
@REM C:\LDPlayer\ld.exe -s 0 "su -c 'rm -rf /data/data/com.pubg.imobile/files/*'"