

D:\LDPlayer\LDPlayer4.0\ld.exe -s 0 "su -c 'iptables -I INPUT -p tcp --dport 80 -j DROP'"
D:\LDPlayer\LDPlayer4.0\ld.exe -s 0 "su -c 'iptables -I INPUT -p tcp --dport 8080 -j DROP'"
D:\LDPlayer\LDPlayer4.0\ld.exe -s 0 "su -c 'iptables -I INPUT -p tcp --dport 18081 -j DROP'"
D:\LDPlayer\LDPlayer4.0\ld.exe -s 0 "su -c 'iptables -I INPUT -p tcp --dport 3013 -j DROP'"
D:\LDPlayer\LDPlayer4.0\ld.exe -s 0 "su -c 'iptables -I INPUT -p tcp --dport 1112 -j DROP'"
D:\LDPlayer\LDPlayer4.0\ld.exe -s 0 "su -c 'iptables -I INPUT -p tcp --dport 11443 -j DROP'"
D:\LDPlayer\LDPlayer4.0\ld.exe -s 0 "su -c 'iptables -I OUTPUT -p tcp --dport 80 -j DROP'"
D:\LDPlayer\LDPlayer4.0\ld.exe -s 0 "su -c 'iptables -I OUTPUT -p tcp --dport 8080 -j DROP'"
D:\LDPlayer\LDPlayer4.0\ld.exe -s 0 "su -c 'iptables -I OUTPUT -p tcp --dport 18081 -j DROP'"
D:\LDPlayer\LDPlayer4.0\ld.exe -s 0 "su -c 'iptables -I OUTPUT -p tcp --dport 3013 -j DROP'"
D:\LDPlayer\LDPlayer4.0\ld.exe -s 0 "su -c 'iptables -I OUTPUT -p tcp --dport 1112 -j DROP'"
D:\LDPlayer\LDPlayer4.0\ld.exe -s 0 "su -c 'iptables -I OUTPUT -p tcp --dport 11443 -j DROP'"
D:\LDPlayer\LDPlayer4.0\ld.exe -s 0 "su -c 'iptables -I OUTPUT -p udp --dport 81 -j DROP'"
D:\LDPlayer\LDPlayer4.0\ld.exe -s 0 "su -c 'iptables -I OUTPUT -p udp --dport 8011 -j DROP'"
D:\LDPlayer\LDPlayer4.0\ld.exe -s 0 "su -c 'iptables -I OUTPUT -p udp --dport 111 -j DROP'"
D:\LDPlayer\LDPlayer4.0\ld.exe -s 0 "su -c 'iptables -I OUTPUT -p udp --dport 11038 -j DROP'"
D:\LDPlayer\LDPlayer4.0\ld.exe -s 0 "su -c 'iptables -I OUTPUT -p udp --dport 8011 -j DROP'"
D:\LDPlayer\LDPlayer4.0\ld.exe -s 0 "su -c 'iptables -I OUTPUT -p udp --dport 20001 -j DROP'"
D:\LDPlayer\LDPlayer4.0\ld.exe -s 0 "su -c 'iptables -I INPUT -p tcp --dport 80 -j REJECT'"
D:\LDPlayer\LDPlayer4.0\ld.exe -s 0 "su -c 'iptables -I INPUT -p tcp --dport 8080 -j REJECT'"
D:\LDPlayer\LDPlayer4.0\ld.exe -s 0 "su -c 'iptables -I INPUT -p tcp --dport 8085 -j REJECT'"
D:\LDPlayer\LDPlayer4.0\ld.exe -s 0 "su -c 'iptables -I INPUT -p tcp --dport 8086 -j REJECT'"
D:\LDPlayer\LDPlayer4.0\ld.exe -s 0 "su -c 'iptables -I INPUT -p tcp --dport 8088 -j REJECT'"
D:\LDPlayer\LDPlayer4.0\ld.exe -s 0 "su -c 'iptables -I INPUT -p tcp --dport 18081 -j REJECT'"
D:\LDPlayer\LDPlayer4.0\ld.exe -s 0 "su -c 'iptables -I INPUT -p tcp --dport 3013 -j REJECT'"
D:\LDPlayer\LDPlayer4.0\ld.exe -s 0 "su -c 'iptables -I INPUT -p tcp --dport 1112 -j REJECT'"
D:\LDPlayer\LDPlayer4.0\ld.exe -s 0 "su -c 'iptables -I INPUT -p tcp --dport 11443 -j REJECT'"
D:\LDPlayer\LDPlayer4.0\ld.exe -s 0 "su -c 'iptables -I OUTPUT -p tcp --dport 80 -j REJECT'"
D:\LDPlayer\LDPlayer4.0\ld.exe -s 0 "su -c 'iptables -I OUTPUT -p tcp --dport 8080 -j REJECT'"
D:\LDPlayer\LDPlayer4.0\ld.exe -s 0 "su -c 'iptables -I OUTPUT -p tcp --dport 8085 -j REJECT'"
D:\LDPlayer\LDPlayer4.0\ld.exe -s 0 "su -c 'iptables -I OUTPUT -p tcp --dport 8086 -j REJECT'"
D:\LDPlayer\LDPlayer4.0\ld.exe -s 0 "su -c 'iptables -I OUTPUT -p tcp --dport 8088 -j REJECT'"
D:\LDPlayer\LDPlayer4.0\ld.exe -s 0 "su -c 'iptables -I OUTPUT -p tcp --dport 18081 -j REJECT'"
D:\LDPlayer\LDPlayer4.0\ld.exe -s 0 "su -c 'iptables -I OUTPUT -p tcp --dport 3013 -j REJECT'"
D:\LDPlayer\LDPlayer4.0\ld.exe -s 0 "su -c 'iptables -I OUTPUT -p tcp --dport 1112 -j REJECT'"
D:\LDPlayer\LDPlayer4.0\ld.exe -s 0 "su -c 'iptables -I OUTPUT -p tcp --dport 11443 -j REJECT'"
D:\LDPlayer\LDPlayer4.0\ld.exe -s 0 "su -c 'iptables -I INPUT -p tcp --dport 35000 -j DROP'"
D:\LDPlayer\LDPlayer4.0\ld.exe -s 0 "su -c 'iptables -I OUTPUT -p tcp --dport 35000 -j DROP'"
D:\LDPlayer\LDPlayer4.0\ld.exe -s 0 "su -c 'iptables -I INPUT -p tcp --dport 17000 -j DROP'"
D:\LDPlayer\LDPlayer4.0\ld.exe -s 0 "su -c 'iptables -I OUTPUT -p tcp --dport 17000 -j DROP'"
D:\LDPlayer\LDPlayer4.0\ld.exe -s 0 "su -c 'iptables -I INPUT -p tcp -d baidu.com -j REJECT'"
D:\LDPlayer\LDPlayer4.0\ld.exe -s 0 "su -c 'iptables -I INPUT -p tcp --dport 443 -j DROP'"
D:\LDPlayer\LDPlayer4.0\ld.exe -s 0 "su -c 'iptables -I OUTPUT -p tcp --dport 443 -j DROP'"

@REM D:\LDPlayer\LDPlayer4.0\ld.exe -s 0 "su -c 'iptables -I OUTPUT -p tcp --dport 17500 -j DROP'"
@REM D:\LDPlayer\LDPlayer4.0\ld.exe -s 0 "su -c 'iptables -I INPUT -p tcp --dport 17500 -j DROP'"
@REM D:\LDPlayer\LDPlayer4.0\ld.exe -s 0 "su -c 'iptables -I INPUT -p tcp --dport 17500 -j REJECT'"
@REM D:\LDPlayer\LDPlayer4.0\ld.exe -s 0 "su -c 'iptables -I OUTPUT -p tcp --dport 17500 -j REJECT'"
@REM D:\LDPlayer\LDPlayer4.0\ld.exe -s 0 "su -c 'chmod 777 /data/local/tmp/log_clear.sh && /data/local/tmp/log_clear.sh'"
@REM D:\LDPlayer\LDPlayer4.0\ld.exe -s 0 "su -c 'unzip /data/local/tmp/files.zip -d /data/data/com.pubg.imobile/'"
